document.addEventListener("DOMContentLoaded", function () {
  document
    .querySelectorAll('[contenteditable="true"]:not(.info-block__note)')
    .forEach((el) => {
      el.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          e.preventDefault();
        }
      });
    });

  //memo
  document.querySelectorAll(".info-block__note").forEach((el) => {
    const placeholder = el.textContent;

    el.addEventListener("focus", () => {
      if (el.textContent === placeholder) {
        el.textContent = "";
      }
    });

    el.addEventListener("blur", () => {
      if (el.textContent.trim() === "") {
        el.textContent = placeholder;
      }
    });
  });

  // badge emoji slot
  const EMOJI_CATEGORIES = [
    {
      name: "스마일리 · 감정",
      icon: "😀",
      emojis: [
        "😀",
        "😃",
        "😄",
        "😁",
        "😆",
        "😅",
        "🤣",
        "😂",
        "🙂",
        "🙃",
        "🫠",
        "😉",
        "😊",
        "😇",
        "🥰",
        "😍",
        "🤩",
        "😘",
        "😗",
        "☺️",
        "😚",
        "😙",
        "🥲",
        "😋",
        "😛",
        "😜",
        "🤪",
        "😝",
        "🤑",
        "🤗",
        "🤭",
        "🫢",
        "🫣",
        "🤫",
        "🤔",
        "🫡",
        "🤐",
        "🤨",
        "😐",
        "😑",
        "😶",
        "🫥",
        "😶‍🌫️",
        "😏",
        "😒",
        "🙄",
        "😬",
        "🤥",
        "🫨",
        "😌",
        "😔",
        "😪",
        "🤤",
        "😴",
        "😷",
        "🤒",
        "🤕",
        "🤢",
        "🤮",
        "🤧",
        "🥵",
        "🥶",
        "🥴",
        "😵",
        "😵‍💫",
        "🤯",
        "🤠",
        "🥳",
        "🥸",
        "😎",
        "🤓",
        "🧐",
        "😕",
        "🫤",
        "😟",
        "🙁",
        "☹️",
        "😮",
        "😯",
        "😲",
        "😳",
        "🥺",
        "🥹",
        "😦",
        "😧",
        "😨",
        "😰",
        "😥",
        "😢",
        "😭",
        "😱",
        "😖",
        "😣",
        "😞",
        "😓",
        "😩",
        "😫",
        "🥱",
        "😤",
        "😡",
        "😠",
        "🤬",
        "😈",
        "👿",
        "💀",
        "☠️",
        "💩",
        "🤡",
        "👹",
        "👺",
        "👻",
        "👽",
        "👾",
        "🤖",
        "😺",
        "😸",
        "😹",
        "😻",
        "😼",
        "😽",
        "🙀",
        "😿",
        "😾",
      ],
    },
    {
      name: "사람 · 신체",
      icon: "🙌",
      emojis: [
        "👋",
        "🤚",
        "🖐️",
        "✋",
        "🖖",
        "🫱",
        "🫲",
        "🫳",
        "🫴",
        "🫷",
        "🫸",
        "👌",
        "🤌",
        "🤏",
        "✌️",
        "🤞",
        "🫰",
        "🤟",
        "🤘",
        "🤙",
        "👈",
        "👉",
        "👆",
        "🖕",
        "👇",
        "☝️",
        "🫵",
        "👍",
        "👎",
        "✊",
        "👊",
        "🤛",
        "🤜",
        "👏",
        "🙌",
        "🫶",
        "👐",
        "🤲",
        "🤝",
        "🙏",
        "✍️",
        "💅",
        "🤳",
        "💪",
        "🦾",
        "🦿",
        "🦵",
        "🦶",
        "👂",
        "🦻",
        "👃",
        "🧠",
        "🫀",
        "🫁",
        "🦷",
        "🦴",
        "👀",
        "👁️",
        "👅",
        "👄",
        "🫦",
        "👶",
        "🧒",
        "👦",
        "👧",
        "🧑",
        "👱",
        "👨",
        "🧔",
        "👩",
        "🧓",
        "👴",
        "👵",
        "🙍",
        "🙎",
        "🙅",
        "🙆",
        "💁",
        "🙋",
        "🧏",
        "🙇",
        "🤦",
        "🤷",
        "👮",
        "🕵️",
        "💂",
        "🥷",
        "👷",
        "🫅",
        "🤴",
        "👸",
        "👳",
        "👲",
        "🧕",
        "🤵",
        "👰",
        "🤰",
        "🫃",
        "🫄",
        "🤱",
        "👼",
        "🎅",
        "🤶",
        "🦸",
        "🦹",
        "🧙",
        "🧚",
        "🧛",
        "🧜",
        "🧝",
        "🧞",
        "🧟",
        "🧌",
        "💆",
        "💇",
        "🚶",
        "🧍",
        "🧎",
        "🏃",
        "💃",
        "🕺",
        "🕴️",
        "👯",
        "🧖",
        "🧗",
        "🤺",
        "🏇",
        "⛷️",
        "🏂",
        "🏌️",
        "🏄",
        "🚣",
        "🏊",
        "⛹️",
        "🏋️",
        "🚴",
        "🚵",
        "🤸",
        "🤼",
        "🤽",
        "🤾",
        "🤹",
        "🧘",
        "🛀",
        "🛌",
        "👭",
        "👫",
        "👬",
        "💏",
        "💑",
        "👪",
      ],
    },
    {
      name: "동물 · 자연",
      icon: "🐶",
      emojis: [
        "🐵",
        "🐒",
        "🦍",
        "🦧",
        "🐶",
        "🐕",
        "🦮",
        "🐩",
        "🐺",
        "🦊",
        "🦝",
        "🐱",
        "🐈",
        "🐈‍⬛",
        "🦁",
        "🐯",
        "🐅",
        "🐆",
        "🐴",
        "🐎",
        "🦄",
        "🦓",
        "🦌",
        "🦬",
        "🐮",
        "🐂",
        "🐃",
        "🐄",
        "🐷",
        "🐖",
        "🐗",
        "🐽",
        "🐏",
        "🐑",
        "🐐",
        "🐪",
        "🐫",
        "🦙",
        "🦒",
        "🐘",
        "🦣",
        "🦏",
        "🦛",
        "🐭",
        "🐁",
        "🐀",
        "🐹",
        "🐰",
        "🐇",
        "🐿️",
        "🦫",
        "🦔",
        "🦇",
        "🐻",
        "🐻‍❄️",
        "🐨",
        "🐼",
        "🦥",
        "🦦",
        "🦨",
        "🦘",
        "🦡",
        "🐾",
        "🦃",
        "🐔",
        "🐓",
        "🐣",
        "🐤",
        "🐥",
        "🐦",
        "🐧",
        "🕊️",
        "🦅",
        "🦆",
        "🦢",
        "🦉",
        "🦤",
        "🪶",
        "🦩",
        "🦚",
        "🦜",
        "🪽",
        "🐸",
        "🐊",
        "🐢",
        "🦎",
        "🐍",
        "🐲",
        "🐉",
        "🦕",
        "🦖",
        "🐳",
        "🐋",
        "🐬",
        "🦭",
        "🐟",
        "🐠",
        "🐡",
        "🦈",
        "🐙",
        "🐚",
        "🪸",
        "🪼",
        "🐌",
        "🦋",
        "🐛",
        "🐜",
        "🐝",
        "🪲",
        "🐞",
        "🦗",
        "🪳",
        "🕷️",
        "🕸️",
        "🦂",
        "🦟",
        "🪰",
        "🪱",
        "🦠",
        "💐",
        "🌸",
        "💮",
        "🪷",
        "🏵️",
        "🌹",
        "🥀",
        "🌺",
        "🌻",
        "🌼",
        "🌷",
        "🪻",
        "🌱",
        "🪴",
        "🌲",
        "🌳",
        "🌴",
        "🌵",
        "🌾",
        "🌿",
        "☘️",
        "🍀",
        "🍁",
        "🍂",
        "🍃",
        "🪹",
        "🪺",
        "🍄",
        "🌰",
      ],
    },
    {
      name: "음식 · 음료",
      icon: "🍔",
      emojis: [
        "🍇",
        "🍈",
        "🍉",
        "🍊",
        "🍋",
        "🍌",
        "🍍",
        "🥭",
        "🍎",
        "🍏",
        "🍐",
        "🍑",
        "🍒",
        "🍓",
        "🫐",
        "🥝",
        "🍅",
        "🫒",
        "🥥",
        "🥑",
        "🍆",
        "🥔",
        "🥕",
        "🌽",
        "🌶️",
        "🫑",
        "🥒",
        "🥬",
        "🥦",
        "🧄",
        "🧅",
        "🍄",
        "🥜",
        "🫘",
        "🌰",
        "🍞",
        "🥐",
        "🥖",
        "🫓",
        "🥨",
        "🥯",
        "🥞",
        "🧇",
        "🧀",
        "🍖",
        "🍗",
        "🥩",
        "🥓",
        "🍔",
        "🍟",
        "🍕",
        "🌭",
        "🥪",
        "🌮",
        "🌯",
        "🫔",
        "🥙",
        "🧆",
        "🥚",
        "🍳",
        "🥘",
        "🍲",
        "🫕",
        "🥣",
        "🥗",
        "🍿",
        "🧈",
        "🧂",
        "🥫",
        "🍱",
        "🍘",
        "🍙",
        "🍚",
        "🍛",
        "🍜",
        "🍝",
        "🍠",
        "🍢",
        "🍣",
        "🍤",
        "🍥",
        "🥮",
        "🍡",
        "🥟",
        "🥠",
        "🥡",
        "🦀",
        "🦞",
        "🦐",
        "🦑",
        "🦪",
        "🍦",
        "🍧",
        "🍨",
        "🍩",
        "🍪",
        "🎂",
        "🍰",
        "🧁",
        "🥧",
        "🍫",
        "🍬",
        "🍭",
        "🍮",
        "🍯",
        "🍼",
        "🥛",
        "☕",
        "🫖",
        "🍵",
        "🍶",
        "🍾",
        "🍷",
        "🍸",
        "🍹",
        "🍺",
        "🍻",
        "🥂",
        "🥃",
        "🫗",
        "🥤",
        "🧋",
        "🧃",
        "🧉",
        "🧊",
        "🥢",
        "🍽️",
        "🍴",
        "🥄",
      ],
    },
    {
      name: "여행 · 장소",
      icon: "✈️",
      emojis: [
        "🌍",
        "🌎",
        "🌏",
        "🌐",
        "🗺️",
        "🗾",
        "🧭",
        "🏔️",
        "⛰️",
        "🌋",
        "🗻",
        "🏕️",
        "🏖️",
        "🏜️",
        "🏝️",
        "🏞️",
        "🏟️",
        "🏛️",
        "🏗️",
        "🧱",
        "🪨",
        "🪵",
        "🛖",
        "🏘️",
        "🏚️",
        "🏠",
        "🏡",
        "🏢",
        "🏣",
        "🏤",
        "🏥",
        "🏦",
        "🏨",
        "🏩",
        "🏪",
        "🏫",
        "🏬",
        "🏭",
        "🏯",
        "🏰",
        "💒",
        "🗼",
        "🗽",
        "⛪",
        "🕌",
        "🛕",
        "🕍",
        "⛩️",
        "🕋",
        "⛲",
        "⛺",
        "🌁",
        "🌃",
        "🏙️",
        "🌄",
        "🌅",
        "🌆",
        "🌇",
        "🌉",
        "🎠",
        "🎡",
        "🎢",
        "💈",
        "🎪",
        "🚂",
        "🚃",
        "🚄",
        "🚅",
        "🚆",
        "🚇",
        "🚈",
        "🚉",
        "🚊",
        "🚝",
        "🚞",
        "🚋",
        "🚌",
        "🚍",
        "🚎",
        "🚐",
        "🚑",
        "🚒",
        "🚓",
        "🚔",
        "🚕",
        "🚖",
        "🚗",
        "🚘",
        "🚙",
        "🛻",
        "🚚",
        "🚛",
        "🚜",
        "🏎️",
        "🏍️",
        "🛵",
        "🦽",
        "🦼",
        "🛺",
        "🚲",
        "🛴",
        "🛹",
        "🛼",
        "🚏",
        "🛣️",
        "🛤️",
        "🛢️",
        "⛽",
        "🛞",
        "🚨",
        "🚥",
        "🚦",
        "🛑",
        "🚧",
        "⚓",
        "🛟",
        "⛵",
        "🛶",
        "🚤",
        "🛳️",
        "⛴️",
        "🛥️",
        "🚢",
        "✈️",
        "🛩️",
        "🛫",
        "🛬",
        "🪂",
        "💺",
        "🚁",
        "🚟",
        "🚠",
        "🚡",
        "🛰️",
        "🚀",
        "🛸",
        "🛎️",
        "🧳",
        "⌛",
        "⏳",
        "⌚",
        "⏰",
        "⏱️",
        "⏲️",
        "🕰️",
        "🌙",
        "☀️",
        "🌤️",
        "⛅",
        "🌦️",
        "🌧️",
        "⛈️",
        "🌩️",
        "🌨️",
        "❄️",
        "☃️",
        "⛄",
        "🌬️",
        "💨",
        "🌪️",
        "🌫️",
        "🌈",
        "☂️",
        "☔",
        "⚡",
        "❄️",
      ],
    },
    {
      name: "활동 · 스포츠",
      icon: "⚽",
      emojis: [
        "🎃",
        "🎄",
        "🎆",
        "🎇",
        "🧨",
        "✨",
        "🎈",
        "🎉",
        "🎊",
        "🎋",
        "🎍",
        "🎎",
        "🎏",
        "🎐",
        "🎑",
        "🧧",
        "🎀",
        "🎁",
        "🎗️",
        "🎟️",
        "🎫",
        "🎖️",
        "🏆",
        "🏅",
        "🥇",
        "🥈",
        "🥉",
        "⚽",
        "⚾",
        "🥎",
        "🏀",
        "🏐",
        "🏈",
        "🏉",
        "🎾",
        "🥏",
        "🎳",
        "🏏",
        "🏑",
        "🏒",
        "🥍",
        "🏓",
        "🏸",
        "🥊",
        "🥋",
        "🥅",
        "⛳",
        "⛸️",
        "🎣",
        "🤿",
        "🎽",
        "🎿",
        "🛷",
        "🥌",
        "🎯",
        "🪀",
        "🪁",
        "🔫",
        "🎱",
        "🔮",
        "🪄",
        "🎮",
        "🕹️",
        "🎰",
        "🎲",
        "🧩",
        "🧸",
        "🪅",
        "🪩",
        "🪆",
        "♠️",
        "♥️",
        "♦️",
        "♣️",
        "♟️",
        "🃏",
        "🀄",
        "🎴",
        "🎭",
        "🖼️",
        "🎨",
        "🧵",
        "🪡",
        "🧶",
        "🪢",
      ],
    },
    {
      name: "사물",
      icon: "💡",
      emojis: [
        "👓",
        "🕶️",
        "🥽",
        "🥼",
        "🦺",
        "👔",
        "👕",
        "👖",
        "🧣",
        "🧤",
        "🧥",
        "🧦",
        "👗",
        "👘",
        "🥻",
        "🩱",
        "🩲",
        "🩳",
        "👙",
        "👚",
        "👛",
        "👜",
        "👝",
        "🛍️",
        "🎒",
        "🩴",
        "👞",
        "👟",
        "🥾",
        "🥿",
        "👠",
        "👡",
        "🩰",
        "👢",
        "👑",
        "👒",
        "🎩",
        "🎓",
        "🧢",
        "🪖",
        "⛑️",
        "📿",
        "💄",
        "💍",
        "💎",
        "🔇",
        "🔈",
        "🔉",
        "🔊",
        "📢",
        "📣",
        "📯",
        "🔔",
        "🔕",
        "🎼",
        "🎵",
        "🎶",
        "🎙️",
        "🎚️",
        "🎛️",
        "🎤",
        "🎧",
        "📻",
        "🎷",
        "🪗",
        "🎸",
        "🎹",
        "🎺",
        "🎻",
        "🪕",
        "🥁",
        "🪘",
        "📱",
        "📲",
        "☎️",
        "📞",
        "📟",
        "📠",
        "🔋",
        "🪫",
        "🔌",
        "💻",
        "🖥️",
        "🖨️",
        "⌨️",
        "🖱️",
        "🖲️",
        "💽",
        "💾",
        "💿",
        "📀",
        "🧮",
        "🎥",
        "🎞️",
        "📽️",
        "🎬",
        "📺",
        "📷",
        "📸",
        "📹",
        "📼",
        "🔍",
        "🔎",
        "🕯️",
        "💡",
        "🔦",
        "🏮",
        "🪔",
        "📔",
        "📕",
        "📖",
        "📗",
        "📘",
        "📙",
        "📚",
        "📓",
        "📒",
        "📃",
        "📜",
        "📄",
        "📰",
        "🗞️",
        "📑",
        "🔖",
        "🏷️",
        "💰",
        "🪙",
        "💴",
        "💵",
        "💶",
        "💷",
        "💸",
        "💳",
        "🧾",
        "✉️",
        "📧",
        "📨",
        "📩",
        "📤",
        "📥",
        "📦",
        "📫",
        "📪",
        "📬",
        "📭",
        "📮",
        "🗳️",
        "✏️",
        "✒️",
        "🖋️",
        "🖊️",
        "🖌️",
        "🖍️",
        "📝",
        "💼",
        "📁",
        "📂",
        "🗂️",
        "📅",
        "📆",
        "🗒️",
        "🗓️",
        "📇",
        "📈",
        "📉",
        "📊",
        "📋",
        "📌",
        "📍",
        "📎",
        "🖇️",
        "📏",
        "📐",
        "✂️",
        "🗃️",
        "🗄️",
        "🗑️",
        "🔒",
        "🔓",
        "🔏",
        "🔐",
        "🔑",
        "🗝️",
        "🔨",
        "🪓",
        "⛏️",
        "⚒️",
        "🛠️",
        "🗡️",
        "⚔️",
        "💣",
        "🪃",
        "🏹",
        "🛡️",
        "🪚",
        "🔧",
        "🪛",
        "🔩",
        "⚙️",
        "🗜️",
        "⚖️",
        "🦯",
        "🔗",
        "⛓️",
        "🪝",
        "🧰",
        "🧲",
        "🪜",
        "⚗️",
        "🧪",
        "🧫",
        "🧬",
        "🔬",
        "🔭",
        "📡",
        "💉",
        "🩸",
        "💊",
        "🩹",
        "🩼",
        "🩺",
        "🚪",
        "🛗",
        "🪞",
        "🪟",
        "🛏️",
        "🛋️",
        "🪑",
        "🚽",
        "🪠",
        "🚿",
        "🛁",
        "🪤",
        "🪒",
        "🧴",
        "🧷",
        "🧹",
        "🧺",
        "🧻",
        "🪣",
        "🧼",
        "🫧",
        "🪥",
        "🧽",
        "🧯",
        "🛒",
      ],
    },
    {
      name: "기호",
      icon: "❤️",
      emojis: [
        "❤️",
        "🧡",
        "💛",
        "💚",
        "💙",
        "💜",
        "🖤",
        "🤍",
        "🤎",
        "💔",
        "❤️‍🔥",
        "❤️‍🩹",
        "❣️",
        "💕",
        "💞",
        "💓",
        "💗",
        "💖",
        "💘",
        "💝",
        "💟",
        "☮️",
        "✝️",
        "☪️",
        "🕉️",
        "☸️",
        "✡️",
        "🔯",
        "🕎",
        "☯️",
        "☦️",
        "🛐",
        "⛎",
        "♈",
        "♉",
        "♊",
        "♋",
        "♌",
        "♍",
        "♎",
        "♏",
        "♐",
        "♑",
        "♒",
        "♓",
        "🆔",
        "⚛️",
        "🉑",
        "☢️",
        "☣️",
        "📴",
        "📳",
        "🈶",
        "🈚",
        "🈸",
        "🈺",
        "🈷️",
        "✴️",
        "🆚",
        "💮",
        "🉐",
        "㊙️",
        "㊗️",
        "🈴",
        "🈵",
        "🈹",
        "🈲",
        "🅰️",
        "🅱️",
        "🆎",
        "🆑",
        "🅾️",
        "🆘",
        "❌",
        "⭕",
        "🛑",
        "⛔",
        "📛",
        "🚫",
        "💯",
        "💢",
        "♨️",
        "🚷",
        "🚯",
        "🚳",
        "🚱",
        "🔞",
        "📵",
        "🚭",
        "❗",
        "❕",
        "❓",
        "❔",
        "‼️",
        "⁉️",
        "🔅",
        "🔆",
        "〽️",
        "⚠️",
        "🚸",
        "🔱",
        "⚜️",
        "🔰",
        "♻️",
        "✅",
        "🈯",
        "💹",
        "❇️",
        "✳️",
        "❎",
        "🌐",
        "💠",
        "Ⓜ️",
        "🌀",
        "💤",
        "🏧",
        "🚾",
        "♿",
        "🅿️",
        "🛗",
        "🈳",
        "🈂️",
        "🛂",
        "🛃",
        "🛄",
        "🛅",
        "🚹",
        "🚺",
        "🚼",
        "⚧️",
        "🚻",
        "🚮",
        "🎦",
        "📶",
        "🈁",
        "🔣",
        "ℹ️",
        "🔤",
        "🔡",
        "🔠",
        "🆖",
        "🆗",
        "🆙",
        "🆒",
        "🆕",
        "🆓",
        "0️⃣",
        "1️⃣",
        "2️⃣",
        "3️⃣",
        "4️⃣",
        "5️⃣",
        "6️⃣",
        "7️⃣",
        "8️⃣",
        "9️⃣",
        "🔟",
        "🔢",
        "#️⃣",
        "*️⃣",
        "⏏️",
        "▶️",
        "⏸️",
        "⏯️",
        "⏹️",
        "⏺️",
        "⏭️",
        "⏮️",
        "⏩",
        "⏪",
        "⏫",
        "⏬",
        "◀️",
        "🔼",
        "🔽",
        "➡️",
        "⬅️",
        "⬆️",
        "⬇️",
        "↗️",
        "↘️",
        "↙️",
        "↖️",
        "↕️",
        "↔️",
        "↪️",
        "↩️",
        "⤴️",
        "⤵️",
        "🔀",
        "🔁",
        "🔂",
        "🔄",
        "🔃",
        "🎵",
        "🎶",
        "➕",
        "➖",
        "➗",
        "✖️",
        "🟰",
        "♾️",
        "💲",
        "💱",
        "™️",
        "©️",
        "®️",
        "👁️‍🗨️",
        "🔚",
        "🔙",
        "🔛",
        "🔝",
        "🔜",
        "〰️",
        "➰",
        "➿",
        "✔️",
        "☑️",
        "🔘",
        "🔴",
        "🟠",
        "🟡",
        "🟢",
        "🔵",
        "🟣",
        "🟤",
        "⚫",
        "⚪",
        "🟥",
        "🟧",
        "🟨",
        "🟩",
        "🟦",
        "🟪",
        "🟫",
        "⬛",
        "⬜",
        "◼️",
        "◻️",
        "◾",
        "◽",
        "▪️",
        "▫️",
        "🔶",
        "🔷",
        "🔸",
        "🔹",
        "🔺",
        "🔻",
        "💠",
        "🔲",
        "🔳",
      ],
    },
    {
      name: "깃발",
      icon: "🏁",
      emojis: [
        "🏁",
        "🚩",
        "🎌",
        "🏴",
        "🏳️",
        "🏳️‍🌈",
        "🏳️‍⚧️",
        "🏴‍☠️",
        "🇰🇷",
        "🇺🇸",
        "🇯🇵",
        "🇨🇳",
        "🇬🇧",
        "🇫🇷",
        "🇩🇪",
        "🇮🇹",
        "🇪🇸",
        "🇨🇦",
        "🇦🇺",
        "🇧🇷",
        "🇮🇳",
        "🇷🇺",
        "🇲🇽",
        "🇳🇱",
        "🇸🇪",
        "🇨🇭",
        "🇸🇬",
        "🇹🇭",
        "🇻🇳",
        "🇵🇭",
        "🇮🇩",
        "🇹🇼",
        "🇭🇰",
        "🇳🇿",
        "🇦🇷",
        "🇿🇦",
        "🇹🇷",
        "🇸🇦",
        "🇦🇪",
        "🇪🇬",
        "🇵🇹",
        "🇬🇷",
        "🇵🇱",
        "🇦🇹",
        "🇧🇪",
        "🇩🇰",
        "🇫🇮",
        "🇳🇴",
        "🇮🇪",
        "🇮🇱",
        "🇲🇾",
        "🇺🇳",
      ],
    },
  ];

  // twemoji jsDelivr
  const TWEMOJI_OPTIONS = {
    base: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/",
    folder: "svg",
    ext: ".svg",
  };

  let activePopover = null;

  function closePopover() {
    if (activePopover) {
      if (activePopover._reposition) {
        window.removeEventListener("scroll", activePopover._reposition, true);
        window.removeEventListener("resize", activePopover._reposition);
      }
      activePopover.remove();
      activePopover = null;
    }
    document.removeEventListener("click", handlePopoverOutsideClick, true);
  }

  function handlePopoverOutsideClick(e) {
    if (activePopover && !activePopover.contains(e.target)) {
      closePopover();
    }
  }

  function renderEmojiGrid(gridEl, categoryIndex, targetEl) {
    gridEl.innerHTML = "";
    EMOJI_CATEGORIES[categoryIndex].emojis.forEach((emoji) => {
      const btn = document.createElement("button");
      btn.type = "button";
      btn.className = "emoji-popover__item";
      btn.textContent = emoji;
      btn.addEventListener("click", (e) => {
        e.stopPropagation();
        targetEl.textContent = emoji;
        if (window.twemoji) twemoji.parse(targetEl, TWEMOJI_OPTIONS);
        closePopover();
      });
      gridEl.appendChild(btn);
    });
    if (window.twemoji) twemoji.parse(gridEl, TWEMOJI_OPTIONS);
  }

  function positionPopover(popover, targetEl) {
    const rect = targetEl.getBoundingClientRect();
    const popW = popover.offsetWidth || 322;
    const popH = popover.offsetHeight || 120;
    const margin = 6;

    let left = rect.left;
    let top = rect.bottom + margin;

    if (left + popW > window.innerWidth - margin) {
      left = window.innerWidth - popW - margin;
    }
    if (left < margin) left = margin;

    if (top + popH > window.innerHeight - margin) {
      top = rect.top - popH - margin;
    }
    if (top < margin) top = margin;

    popover.style.left = `${left}px`;
    popover.style.top = `${top}px`;
  }

  function openEmojiPopover(targetEl) {
    closePopover();

    const popover = document.createElement("div");
    popover.className = "emoji-popover";

    const tabs = document.createElement("div");
    tabs.className = "emoji-popover__tabs";

    const grid = document.createElement("div");
    grid.className = "emoji-popover__grid";

    EMOJI_CATEGORIES.forEach((category, index) => {
      const tabBtn = document.createElement("button");
      tabBtn.type = "button";
      tabBtn.className = "emoji-popover__tab";
      tabBtn.textContent = category.icon;
      tabBtn.title = category.name;
      tabBtn.setAttribute("aria-label", category.name);
      if (index === 0) tabBtn.classList.add("emoji-popover__tab--active");

      tabBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        tabs
          .querySelectorAll(".emoji-popover__tab")
          .forEach((t) => t.classList.remove("emoji-popover__tab--active"));
        tabBtn.classList.add("emoji-popover__tab--active");
        renderEmojiGrid(grid, index, targetEl);
      });

      tabs.appendChild(tabBtn);
    });

    popover.appendChild(tabs);
    popover.appendChild(grid);
    renderEmojiGrid(grid, 0, targetEl);
    if (window.twemoji) twemoji.parse(tabs, TWEMOJI_OPTIONS);

    document.body.appendChild(popover);
    activePopover = popover;
    positionPopover(popover, targetEl);

    const reposition = () => positionPopover(popover, targetEl);
    window.addEventListener("scroll", reposition, true);
    window.addEventListener("resize", reposition);
    popover._reposition = reposition;

    setTimeout(() => {
      document.addEventListener("click", handlePopoverOutsideClick, true);
    }, 0);
  }

  document.querySelectorAll('[data-emoji-slot="true"]').forEach((el) => {
    el.addEventListener("click", (e) => {
      e.stopPropagation();
      if (activePopover && el.contains(activePopover)) {
        closePopover();
      } else {
        openEmojiPopover(el);
      }
    });
  });

  // coloris
  if (window.Coloris) {
    Coloris({
      el: ".role-list__color-input",
      wrap: false,
      theme: "pill",
      themeMode: "dark",
      format: "hex",
      alpha: false,
      focusInput: false,
    });

    // badge background color
    document.addEventListener("coloris:pick", (event) => {
      const input = event.detail.currentEl;
      if (input && input.classList.contains("role-list__color-input")) {
        const badge = input.closest(".role-list__badge");
        if (badge) badge.style.background = event.detail.color;
      }
    });
  }

  // twitter emoji rendering
  if (window.twemoji) {
    twemoji.parse(document.body, TWEMOJI_OPTIONS);
  }

  // ── 카드(보드) 사진 삽입 & 드래그 이동 ─────────────────────────
  document.querySelectorAll("[data-photo-card]").forEach((card) => {
    const input = card.querySelector(".card__file-input");
    const img = card.querySelector(".card__photo");
    if (!input || !img) return;

    const state = {
      naturalW: 0,
      naturalH: 0,
      baseScale: 1,
      scale: 1,
      offsetX: 0,
      offsetY: 0,
    };

    function render() {
      const s = state.baseScale * state.scale;
      img.style.width = `${state.naturalW * s}px`;
      img.style.height = `${state.naturalH * s}px`;
      img.style.transform = `translate(${state.offsetX}px, ${state.offsetY}px)`;
    }

    function clampOffset() {
      const w = card.clientWidth;
      const h = card.clientHeight;
      const s = state.baseScale * state.scale;
      const imgW = state.naturalW * s;
      const imgH = state.naturalH * s;
      const minX = Math.min(0, w - imgW);
      const minY = Math.min(0, h - imgH);
      state.offsetX = Math.min(0, Math.max(minX, state.offsetX));
      state.offsetY = Math.min(0, Math.max(minY, state.offsetY));
    }

    function loadFile(file) {
      if (!file || !file.type || !file.type.startsWith("image/")) return;
      const url = URL.createObjectURL(file);
      const probe = new Image();
      probe.onload = () => {
        state.naturalW = probe.naturalWidth;
        state.naturalH = probe.naturalHeight;
        const w = card.clientWidth;
        const h = card.clientHeight;
        state.baseScale = Math.max(w / state.naturalW, h / state.naturalH);
        state.scale = 1;
        const s = state.baseScale;
        state.offsetX = (w - state.naturalW * s) / 2;
        state.offsetY = (h - state.naturalH * s) / 2;
        img.src = url;
        card.classList.add("has-photo");
        clampOffset();
        render();
      };
      probe.src = url;
    }

    // 카드 클릭 시 사진 선택 (드래그 직후에는 열지 않음)
    let dragMoved = false;
    card.addEventListener("click", () => {
      if (dragMoved) return;
      input.click();
    });

    input.addEventListener("change", (e) => {
      const file = e.target.files && e.target.files[0];
      if (file) loadFile(file);
      input.value = "";
    });

    // 마우스로 사진 위치 이동
    let dragging = false;
    let startX = 0;
    let startY = 0;
    let startOffsetX = 0;
    let startOffsetY = 0;

    img.addEventListener("mousedown", (e) => {
      if (!state.naturalW) return;
      dragging = true;
      dragMoved = false;
      startX = e.clientX;
      startY = e.clientY;
      startOffsetX = state.offsetX;
      startOffsetY = state.offsetY;
      card.classList.add("is-dragging");
      e.preventDefault();
      e.stopPropagation();
    });

    window.addEventListener("mousemove", (e) => {
      if (!dragging) return;
      const dx = e.clientX - startX;
      const dy = e.clientY - startY;
      if (Math.abs(dx) > 2 || Math.abs(dy) > 2) dragMoved = true;
      state.offsetX = startOffsetX + dx;
      state.offsetY = startOffsetY + dy;
      clampOffset();
      render();
    });

    window.addEventListener("mouseup", () => {
      if (!dragging) return;
      dragging = false;
      card.classList.remove("is-dragging");
      // click 이벤트가 mouseup 직후 발생하므로 살짝 지연 후 플래그 해제
      setTimeout(() => {
        dragMoved = false;
      }, 0);
    });

    // 마우스 휠로 확대/축소 (선택 기능)
    card.addEventListener(
      "wheel",
      (e) => {
        if (!state.naturalW) return;
        e.preventDefault();
        const delta = e.deltaY < 0 ? 1.08 : 0.92;
        state.scale = Math.min(4, Math.max(1, state.scale * delta));
        clampOffset();
        render();
      },
      { passive: false },
    );
  });
});
